version: "3.8"
services:
    #Postgres
    database:
        image: postgres
        environment: 
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: Gianluca.96
            POSTGRES_DB: facedetection
            POSTGRES_HOST: postgres
        build: ./postgres
        ports: 
            - "5432:5432"
        

    #backend API 
    face-detection-api:
        container_name: backend
        build: ./
        command: npm start
        working_dir: /usr/src/face-detection-web-site-api
        environment: 
            POSTGRES_URL: postgres://postgres:Gianluca.96@postgres:5432/facedetection
        links:  
            - database
        ports:
            - "3000:3000" 
        volumes: 
            - ./:/usr/src/face-detection-web-site-api

    
