version: "3.8"
services:
    #Postgres
    database:
        image: postgres:13
        container_name: postgres
        environment: 
            POSTGRES_USER: productioncoder
            POSTGRES_DB: facedetection
            POSTGRES_HOST_AUTH_METHOD: trust
            POSTGRES_PASSWORD: secret
        build: ./postgres
        ports: 
            - "2345:5432"
        

    #backend API 
    face-detection-api:
        container_name: backend
        build: ./
        command: npm start
        working_dir: /usr/src/face-detection-web-site-api
        environment: 
            DB_URI: postgres://productioncoder:secret@postgres:5432/facedetection
        depends_on: 
            - database
        ports:
            - "3000:3000" 
        volumes: 
            - ./:/usr/src/face-detection-web-site-api

    
