version: "3.8"
services: 
    face-detection-api:
        container_name: backend
        image: node:12.18.4
        build: ./
        command: npm start
        working_dir: /usr/src/face-detection-web-site-api
        ports:
            - "3000:3000" 
        volumes: 
            - ./:/usr/src/face-detection-web-site-api